import { useState } from "react";

export default function Content() {
  const [num, setNum] = useState(0);
  const incNum = () => {
    setNum((n) => n + 1);
  };
  const decNum = () => {
    setNum((n) => n - 1);
  };
  const resetNum = () => {
    setNum(0);
  };
  return (
    <div>
      <article>
        <h2>Hello!</h2>
        <p>This content is generated by client side!</p>
        <div>
          {num}
          <div>
            <button onClick={decNum}>-</button>
            <button onClick={incNum}>+</button>
            <button onClick={resetNum}>reset</button>
          </div>
        </div>
      </article>
    </div>
  );
}
